name: Provision AWS (Terraform) - Action 2

on:
  workflow_dispatch:
    inputs:
      accion:
        description: "apply | destroy"
        required: true
        default: "apply"
      cod_servicio:
        description: "CÃ³digo del microservicio (ej: demo-01)"
        required: true
      tecnologia:
        description: "Java|Node|Net"
        required: true
        default: "Java"

jobs:
  provision:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TF }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init -reconfigure \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=services/${{ inputs.cod_servicio }}.tfstate" \
          -backend-config="region=${{ secrets.TF_STATE_REGION }}"

      # APPLY
      - name: Terraform Apply
        if: inputs.accion == 'apply'
        working-directory: infra
        env:
          TF_VAR_cod_servicio: ${{ inputs.cod_servicio }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_crear_apprunner: true
        run: terraform apply -auto-approve
    
      # DESTROY
      - name: Terraform Destroy
        if: inputs.accion == 'destroy'
        working-directory: infra
        env:
          TF_VAR_cod_servicio: ${{ inputs.cod_servicio }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
        run: terraform destroy -auto-approve

      - name: Export AWS account id
        if: inputs.accion == 'apply'
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Export Terraform outputs
        if: inputs.accion == 'apply'
        working-directory: infra
        run: |
          echo "ECR_REPO=$(terraform output -raw ecr_repo_name)" >> $GITHUB_ENV
          echo "ECR_REPO_ARN=$(terraform output -raw ecr_repo_arn)" >> $GITHUB_ENV
          echo "ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV
          echo "ECR_REPOSITORY_ARN=$(terraform output -raw ecr_repo_arn)" >> $GITHUB_ENV
          echo "APPRUNNER_SERVICE_URL=$(terraform output -raw apprunner_service_url)" >> $GITHUB_ENV
          echo "APPRUNNER_SERVICE_ARN=$(terraform output -raw apprunner_service_arn)" >> $GITHUB_ENV
       

      - name: Update Port (estado)
        if: always()
        env:
          PORT_WEBHOOK_URL: ${{ secrets.PORT_WEBHOOK_URL_INFRA }}
          COD_SERVICIO: ${{ inputs.cod_servicio }}
          TECNOLOGIA: ${{ inputs.tecnologia }}
          ACCION: ${{ inputs.accion }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
          ECR_REPO: ${{ env.ECR_REPO }}
          ECR_REPOSITORY_URL: ${{ env.ECR_REPOSITORY_URL }}
          ECR_REPOSITORY_ARN: ${{ env.ECR_REPOSITORY_ARN }}
          APPRUNNER_SERVICE_URL: ${{ env.APPRUNNER_SERVICE_URL }}
          APPRUNNER_SERVICE_ARN: ${{ env.APPRUNNER_SERVICE_ARN }}
        run: |
          python scripts/port_provision_update.py
